language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TYPO3_VERSION=^8.7
    - php: 7.1
      env: TYPO3_VERSION=^8.7
    - php: 7.2
      env: TYPO3_VERSION=^8.7
    - php: 7.3
      env: TYPO3_VERSION=^8.7
    - php: 7.2
      env: TYPO3_VERSION=^9.5
    - php: 7.3
      env: TYPO3_VERSION=^9.5

sudo: false

before_script:
  - composer require typo3/minimal="$TYPO3_VERSION"
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - .Build/bin/phpcs -n --standard=PSR2 --extensions=php *
  - .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  - >
      echo;
      export typo3DatabaseName="typo3_test";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional/